services:
  - type: web
    name: happy-burger
    runtime: python
    region: oregon        # o la regi√≥n que prefieras en Render
    plan: free            # mientras sea un proyecto escolar, el free suele bastar
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
